"""empty message

Revision ID: 3a9358d1b73
Revises: None
Create Date: 2018-04-15 03:56:59.181476

"""

# revision identifiers, used by Alembic.
revision = '3a9358d1b73'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('latitude', 'longitude')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    ### end Alembic commands ###
